README.md, lib/extension.js, lib/index.js, resources/zeebe.json, test/spec/extension.js
Related to https://github.com/zeebe-io/zeebe-modeler/issues/248
=> Implement zeebe moddle extension and canCopyProperty

resources/zeebe.json, test/fixtures/xml/process-zeebe-userTaskForm.part.bpmn, test/spec/xml/read.js, test/spec/xml/write.js
Verifies XML entity encoding in body elements (not working right now) :fire:.
Builds upon https://github.com/zeebe-io/zeebe-bpmn-moddle/pull/11.
=> Xml entity

resources/zeebe.json, test/spec/extension.js
__Current Situation__
* TaskDefinition property doesn't have the `meta.allowedIn` field in the zeebe.json
__Problem__
* For properties without the `meta.allowedIn` field, it is assumed to be allowed for all elements 
* Doesn't make sense since it's only present for zeebe Service Tasks 
__Solution__
* Add  `zeebeServiceTasks` in the `meta.allowedIn` field for the `taskDefinition` property in the zeebe.json
=> fix: restrict `taskDefinition` for `zeebeServiceTasks` only

lib/extension.js, resources/zeebe.json, test/spec/extension.js
- Make  Message Intermediate Throw Event and Message End Event `zeebeServiceTask`
- Tweak `canCopyProperty` behaviour to ensure only message End Events and Intermediate Throw Events (with message definitions) are able to host `zeebeServiceTask` properties
Related to https://github.com/camunda/camunda-modeler/issues/2420
=> Make Message Intermediate Throw Event and Message End Event Zeebe Service Tasks

README.md, package.json
* After this commit, I will move the repo to camunda-cloud org
related to bpmn-io/internal-docs#292
=> chore: change links from zeebe-io to camunda-cloud org

resources/zeebe.json, test/fixtures/xml/task-modelerTemplate.part.bpmn, test/fixtures/xml/task-modelerTemplateVersion.part.bpmn, test/spec/xml/read.js, test/spec/xml/write.js
Related to bpmn-io/bpmn-js-properties-panel#540
Related to bpmn-io/bpmn-js-properties-panel#555
=> feat(zeebe): add `modelerTemplate` and `modelerTemplateVersion`

resources/zeebe.json, test/fixtures/xml/task-modelerTemplateIcon.part.bpmn, test/spec/xml/read.js, test/spec/xml/write.js
Closes #23
Example
```xml
<bpmn:serviceTask id="Activity_08bosyf" zeebe:modelerTemplate="icon.template.sendgrid18">
<bpmn:extensionElements>
<zeebe:modelerTemplateIcon>data:image/svg+xml,%3Csvg width='16' height='16' viewBox='0 0 16 16' fill='none' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath d='M1.14264 5.69666H5.72264V10.2767H1.14264V5.69666V5.69666Z' fill='white'/%3E%3Cpath d='M1.14264 5.69666H5.72264V10.2767H1.14264V5.69666V5.69666Z' fill='%2399E1F4'/%3E%3Cpath d='M5.72333 10.2767H10.2767V14.83H5.72333V10.2767V10.2767Z' fill='white'/%3E%3Cpath d='M5.72333 10.2767H10.2767V14.83H5.72333V10.2767V10.2767Z' fill='%2399E1F4'/%3E%3Cpath d='M1.14264 14.8307H5.72264V14.8573H1.14264V14.8307V14.8307ZM1.14264 10.2773H5.72264V14.8307H1.14264V10.2773V10.2773Z' fill='%231A82E2'/%3E%3Cpath …
```
=> feat(zeebe): add `modelerTemplateIcon` property

resources/zeebe.json, test/spec/extension.js
Related to https://github.com/bpmn-io/bpmn-js-properties-panel/issues/738
> npx @bpmn-io/sr camunda/camunda-bpmn-js -l camunda-cloud/zeebe-bpmn-moddle#738-lost-task-headers -c "npm run start:cloud"
=> fix(extension): allow copy extensions to user task

CHANGELOG.md, resources/zeebe.json, test/fixtures/xml/startEvent-zeebe-properties.part.bpmn, test/fixtures/xml/zeebe-properties.bpmn, test/spec/xml/read.js, test/spec/xml/roundtrip.js
Provides support for the newly added [`zeebe:properties` extension point](https://github.com/camunda/zeebe/issues/9868).
----
Closes #30
=> Support `zeebe:properties`

CHANGELOG.md, resources/zeebe.json, test/fixtures/xml/scriptTask-zeebe-script.part.bpmn, test/spec/xml/read.js, test/spec/xml/write.js
Related to https://github.com/camunda/camunda-modeler/issues/3321
=> feat: support `zeebe:script`

CHANGELOG.md, resources/zeebe.json
Will be followed up by a pull request in `bpmn-js-properties-panel` that removes the check for `zeebe:PropertiesHolder`.
---
Closes #43
=> chore: remove `zeebe:PropertiesHolder`

resources/zeebe.json, test/fixtures/xml/userTask-zeebe-taskSchedule.part.bpmn, test/spec/xml/read.js, test/spec/xml/write.js
Adds support for `zeebe:TaskSchedule` extension elements supported by Camunda 8.2.
```xml
<userTask id="UserTask_1">
<extensionElements>
<zeebe:taskSchedule dueDate="2023-04-20T04:20:00Z" followUpDate="=followUpDate" />
</extensionElements>
</userTask>
```
---
Related to https://github.com/camunda/camunda-modeler/issues/3484
=> feat: add `zeebe:TaskSchedule` extension element

CHANGELOG.md, resources/zeebe.json, test/fixtures/xml/rootElement.bpmn, test/spec/xml/read.js, test/spec/xml/roundtrip.js, test/spec/xml/write.js
```xml
<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://www.omg.org/spec/BPMN/20100524/MODEL"
xmlns:zeebe="http://camunda.org/schema/zeebe/1.0"
targetNamespace="http://bpmn.io/schema/bpmn">
<message zeebe:modelerTemplate="templateId"/>
<error zeebe:modelerTemplate="templateId"/>
<signal zeebe:modelerTemplate="templateId"/>
<escalation zeebe:modelerTemplate="templateId"/>
</definitions>
```
Related to https://github.com/camunda/camunda-modeler/issues/3403
=> feat: support templated root elements

resources/zeebe.json, test/fixtures/xml/call-activity-zeebe-calledElement-propagateAllParentVariables.part.bpmn, test/spec/xml/read.js, test/spec/xml/write.js
=> fix: set `propagateAllParentVariables` default value to `true`

resources/zeebe.json, test/fixtures/xml/event-zeebe-executionListener.part.bpmn, test/fixtures/xml/gateway-zeebe-executionListener.part.bpmn, test/fixtures/xml/task-zeebe-executionListener.part.bpmn, test/fixtures/xml/zeebe-execution-listeners.bpmn, test/spec/xml/read.js, test/spec/xml/roundtrip.js, test/spec/xml/write.js
This adds support for `zeebe:ExecutionListener` contained in `zeebe:ExecutionListeners` container. The `allowedIn` property reflects the table from https://github.com/camunda/camunda-docs/pull/4017
Related to https://github.com/camunda/camunda-modeler/issues/3951
=> feat: support zeebe:ExecutionListener

CHANGELOG.md, resources/zeebe.json, test/fixtures/xml/zeebe-versionTag.bpmn, test/fixtures/xml/zeebe-versionTag.part.bpmn, test/spec/xml/read.js, test/spec/xml/roundtrip.js, test/spec/xml/write.js
Adds support for `zeebe:VersionTag` extension elements at the process level.
```xml
<bpmn:process 
id="process-1"
xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL"
xmlns:zeebe="http://camunda.org/schema/zeebe/1.0"
>
<bpmn:extensionElements>
<zeebe:versionTag value="v1.0.0" />
</bpmn:extensionElements>
</bpmn:process>
```
Closes #59
=> feat: support `zeebe:VersionTag`

resources/zeebe.json, test/fixtures/xml/userTask-zeebe-priority.part.bpmn, test/spec/xml/read.js, test/spec/xml/write.js
Closes #62
~One part which wasn't 100% clear to  me was whether we want to make it an integer or not. I saw that integers are very rare in general in the moddle and plenty of integer-y things are parsed as strings. Also priority is one of those things that could theoretically be either really.~
~So not sure, what do you think~
Nevermind I read through some stuff and I saw we need to support feel, so string it is, undrafting this.
=> feat: support `zeebe:priority`

resources/zeebe.json, test/fixtures/xml/userTask-zeebe-priority.part.bpmn, test/spec/xml/read.js, test/spec/xml/write.js
=> fix: rename `zeebe:priority` to `zeebe:priorityDefinition`

resources/zeebe.json, test/fixtures/xml/calledDecision-versionTag.part.bpmn, test/fixtures/xml/calledElement-versionTag.part.bpmn, test/fixtures/xml/formDefinition-versionTag.part.bpmn, test/fixtures/xml/zeebe-bindingType.bpmn, test/spec/xml/read.js, test/spec/xml/write.js
* allows setting the `versionTag` property not only on the linked resource (process) but also on the elements that link to that resource (business rule task, call activity, user task)
Related to https://github.com/camunda/camunda-modeler/issues/4460
Related to https://github.com/camunda/camunda-modeler/issues/4461
Related to https://github.com/camunda/camunda-modeler/issues/4462
=> feat: support `versionTag` on `zeebe:BindingTypeSupported`

resources/zeebe.json, test/fixtures/xml/userTask-zeebe-taskListener.part.bpmn, test/fixtures/xml/zeebe-taskListeners.bpmn, test/spec/xml/read.js, test/spec/xml/roundtrip.js, test/spec/xml/write.js
This adds support for `zeebe:TaskListener` contained in `zeebe:TaskListeners` container.
related to https://github.com/camunda/camunda-modeler/issues/4590
=> feat: support zeebe:TaskListener

resources/zeebe.json, test/fixtures/xml/adhoc-sub-process-zeebe-adHoc.bpmn, test/fixtures/xml/zeebe-adHoc.bpmn, test/spec/xml/read.js, test/spec/xml/roundtrip.js, test/spec/xml/write.js
Add support for `zeebe:AdHoc` in `bpmn:AdHocSubProcess`.
Related to https://github.com/camunda/camunda-modeler/issues/4739
=> feat: support `zeebe:AdHoc`
